### ISSUE TITLE
No such file or directory: 'VERSION'

### ISSUE THREAD

**Issue by etano** [opentracing-contrib/python-elasticsearch#1]
I believe you may need to push your recent changes to PyPi because the current install breaks:

`$ pip install elasticsearch_opentracing
Collecting elasticsearch_opentracing
  Downloading elasticsearch_opentracing-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-8pJUUz/elasticsearch-opentracing/setup.py", line 3, in <module>
        version = open('VERSION').read()
    IOError: [Errno 2] No such file or directory: 'VERSION'`

**Comment by ror6ax** [comment]
Same here. @tedsuo - can you please add me as a maintainer here as well so I can re-release the artifact?

**Comment by carlosalberto** [comment]
Hey @ror6ax Just re-released. Hope this fixes the error. I had issued a release last year (as old versions of `pip` have an issue with `MANIFEST`/`MANIFEST.in`), but it seems it didn't really fix it :/

Synchronizing to PyPi takes a around 15 min, so I will triple check by then. Let me know.
